apiVersion: v1
kind: Service
metadata:
  labels:
    name: microservice
  name: microservice
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3050
  selector:
    name: microservice

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: microservice
  name: microservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: microservice
    spec:
      containers:
      - name: microservice
        image: vizzuality/poc-bigquery-geo:0.0.2
        imagePullPolicy: Always
        args:
          - startkube
        env:
          - name: PORT
            value: "3050"
          - name: GIN_MODE
            value: release
          - name: GCLOUD_PROJECT_ID
            valueFrom:
                secretKeyRef:
                  name: gcloudsecrets
                  key: GCLOUD_PROJECT_ID
          - name: GCLOUD_CREDENTIALS
            valueFrom:
                secretKeyRef:
                  name: gcloudsecrets
                  key: GCLOUD_CREDENTIALS

        ports:
          - containerPort: 3050

      restartPolicy: Always
